'use client';
import {useEffect,useState} from 'react';
import '../merchant.css';
type Row=Record<string,any>;
const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const titles=['Legal business','Store and branding','Store location','Operating hours','Review and submit'];
export default function MerchantRegistration(){
 const [signed,setSigned]=useState(false),[ready,setReady]=useState(false),[application,setApplication]=useState<Row|null>(null),[data,setData]=useState<Row>({timezone:'Africa/Kigali',merchantType:'RESTAURANT',cuisineTags:[],openingHours:days.map(()=>[{open:'09:00',close:'18:00'}])}),[step,setStep]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const call=async(path:string,method='GET',body?:unknown)=>{const r=await fetch(`/api/merchant/${path}`,{method,headers:{'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});const d=await r.json();if(!r.ok)throw Error(d.message||d.error);return d;};
 const resume=async()=>{const rows=await call('applications');const row=rows.find((v:Row)=>['DRAFT','SUBMITTED'].includes(v.status))||rows[0];if(row){setApplication(row);setData(d=>({...d,...row.payload}));setStep(Math.min(row.step,4));}};
 useEffect(()=>{fetch('/api/merchant-session/me').then(async r=>{if(r.ok){setSigned(true);await resume();}}).catch(e=>setError(String(e))).finally(()=>setReady(true));},[]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError(String(e).replace('Error: ',''));}finally{setBusy(false);}};
 const field=(key:string,title:string,type='text')=><label>{title}<input required type={type} step={type==='number'?'any':undefined} value={data[key]??''} onChange={e=>setData({...data,[key]:type==='number'?e.target.valueAsNumber:e.target.value})}/></label>;
 if(!ready)return <main className="mp-loading">Loading your application…</main>;
 return <main className="mp" style={{maxWidth:850,margin:'auto',padding:24}}><a className="mp-brand" href="/merchant">Fida business</a><h1>Bring your store to Fida</h1><p>Your business, your drivers, direct customer payments.</p>{error&&<p className="mp-error" role="alert">{error}</p>}
 {!signed?<form className="mp-panel" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{const r=await fetch('/api/merchant-session/register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(f))});const d=await r.json();if(!r.ok)throw Error(d.message||d.error);setSigned(true);});}}><h2>Create your owner account</h2><label>Your name<input name="firstName" required autoComplete="given-name"/></label><label>Email<input name="email" type="email" required autoComplete="email"/></label><label>Phone<input name="phone" type="tel" required autoComplete="tel"/></label><label>Password<input name="password" type="password" minLength={12} maxLength={128} required autoComplete="new-password"/></label><button disabled={busy}>Create account</button><p>Already registered? <a href="/merchant">Sign in and continue your application</a></p></form>:
 application&&application.status!=='DRAFT'?<section className="mp-panel"><h2>{application.status==='SUBMITTED'?'Awaiting platform review':application.status==='APPROVED'?'Your store is approved':'Application rejected'}</h2><p>{application.reviewReason||'Your store remains hidden until an administrator approves your application.'}</p><button disabled={busy} onClick={()=>void run(resume)}>Check status</button>{application.status==='APPROVED'&&<a href="/merchant">Open your business</a>}{application.status==='REJECTED'&&<button disabled={busy} onClick={()=>void run(async()=>{const row=await call(`applications/${application.id}/reopen`,'POST',{});setApplication(row);setStep(0);})}>Start a corrected application</button>}</section>:
 <form className="mp-panel" onSubmit={e=>{e.preventDefault();void run(async()=>{let row:Row=application??await call('applications','POST',{});setApplication(row);if(step<4){row=await call(`applications/${row.id}`,'PATCH',{stage:step,data});setApplication(row);setStep(step+1);}else{row=await call(`applications/${row.id}/submit`,'POST',{});setApplication(row);}});}}><p>Step {step+1} of 5 · Saved securely as you continue</p><progress value={step+1} max={5}/><h2>{titles[step]}</h2>
 {step===0&&<>{field('legalName','Registered legal entity')}{field('taxId','Tax identification number')}</>}
 {step===1&&<>{field('name','Store display name')}{field('slug','Store URL name')}<label>Business category<select value={data.merchantType} onChange={e=>setData({...data,merchantType:e.target.value})}>{['RESTAURANT','SUPERMARKET','PHARMACY','RETAIL','OTHER'].map(v=><option key={v}>{v}</option>)}</select></label>{field('logoUrl','Logo image HTTPS URL','url')}{field('coverUrl','Cover photo HTTPS URL','url')}{data.coverUrl&&<img alt="Store cover preview" className="mp-preview" src={data.coverUrl}/>}<label>Cuisines / category tags, separated by commas<input required value={data.cuisineTags.join(',')} onChange={e=>setData({...data,cuisineTags:e.target.value.split(',')})}/></label>{field('timezone','Operating time zone')}</>}
 {step===2&&<>{field('addressLine','Street / building address')}{field('city','City')}{field('latitude','Latitude','number')}{field('longitude','Longitude','number')}<button type="button" className="mp-secondary" onClick={()=>navigator.geolocation.getCurrentPosition(p=>setData({...data,latitude:p.coords.latitude,longitude:p.coords.longitude}),e=>setError(e.message))}>Use current location</button></>}
 {step===3&&days.map((day,i)=><fieldset key={day}><legend>{day}</legend>{data.openingHours[i].map((w:Row,j:number)=><div className="mp-form-grid" key={j}>{['open','close'].map(k=><label key={k}>{k}<input type="time" required value={w[k]} onChange={e=>setData({...data,openingHours:data.openingHours.map((v:Row[],d:number)=>d===i?v.map((x,n)=>n===j?{...x,[k]:e.target.value}:x):v)})}/></label>)}<button type="button" className="mp-secondary" onClick={()=>setData({...data,openingHours:data.openingHours.map((v:Row[],d:number)=>d===i?v.filter((_,n)=>n!==j):v)})}>Remove window</button></div>)}{!data.openingHours[i].length&&<p>Closed</p>}<button type="button" disabled={data.openingHours[i].length>=4} onClick={()=>setData({...data,openingHours:data.openingHours.map((v:Row[],d:number)=>d===i?[...v,{open:'09:00',close:'18:00'}]:v)})}>Add opening window</button></fieldset>)}
 {step===4&&<><h3>{data.name}</h3><p>{data.legalName} · Tax ID {data.taxId}</p><p>{data.addressLine}, {data.city} ({data.latitude}, {data.longitude})</p><p>{data.cuisineTags.join(', ')} · {data.timezone}</p>{days.map((day,i)=><p key={day}>{day}: {data.openingHours[i].map((w:Row)=>`${w.open}–${w.close}`).join(', ')||'Closed'}</p>)}<p>Submitting requests administrator approval. You can operate only after approval.</p></>}
 <div className="mp-actions">{step>0&&<button type="button" className="mp-secondary" disabled={busy} onClick={()=>setStep(step-1)}>Back</button>}<button disabled={busy}>{busy?'Saving…':step===4?'Submit for approval':'Save and continue'}</button></div></form>}</main>;
}
