import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { PGlite } from '@electric-sql/pglite';
import { PGLiteSocketServer } from '@electric-sql/pglite-socket';
import { test } from 'node:test';
import {mkdtemp,readFile,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const media=await mkdtemp(join(tmpdir(),'fida-test-media-'));
process.env.MEDIA_DIRECTORY=media;

process.env.APP_ENV = 'test';
process.env.JWT_ACCESS_SECRET = 'local-test-only-secret-at-least-thirty-two-characters';
process.env.DATABASE_URL = 'postgresql://postgres:postgres@127.0.0.1:55439/postgres?connection_limit=1';
delete process.env.FLUTTERWAVE_SECRET_KEY;
delete process.env.FLUTTERWAVE_WEBHOOK_SECRET;
const db = await PGlite.create();
const sql = execFileSync('node_modules/.bin/prisma', ['migrate','diff','--from-empty','--to-schema','packages/database/prisma/schema.prisma','--script'], {encoding:'utf8',env:process.env});
await db.exec(sql);
const socket = new PGLiteSocketServer({db,port:55439,host:'127.0.0.1'});
await socket.start();
const { prisma } = await import('../packages/database/src/client.js');
const { buildServer } = await import('../apps/api/src/server.js');
const app = await buildServer();
await app.ready();
const owner=await prisma.user.create({data:{email:'owner@example.test',phone:'+250788000001'}});
const customer=await prisma.user.create({data:{email:'customer@example.test',phone:'+250788000002'}});
const outsider=await prisma.user.create({data:{email:'outsider@example.test',phone:'+250788000003'}});
const staff=await prisma.user.create({data:{email:'staff@example.test'}});
const admin=await prisma.user.create({data:{email:'admin@example.test',isPlatformAdmin:true}});
const tenant=await prisma.tenant.create({data:{name:'Test Kitchen',slug:'test-kitchen',status:'ACTIVE',merchantType:'RESTAURANT',taxPercent:10,platformCommissionPercent:10}});
const other=await prisma.tenant.create({data:{name:'Other Kitchen',slug:'other-kitchen',status:'ACTIVE',merchantType:'RESTAURANT'}});
await prisma.tenantMembership.createMany({data:[{tenantId:tenant.id,userId:owner.id,role:'OWNER'},{tenantId:tenant.id,userId:staff.id,role:'STAFF'}]});
const branch=await prisma.branch.create({data:{tenantId:tenant.id,name:'Central',latitude:-1.95,longitude:30.05}});
await prisma.deliveryZone.create({data:{branchId:branch.id,minDistanceKm:0,maxDistanceKm:10,fee:500}});
const category=await prisma.category.create({data:{tenantId:tenant.id,name:'Lunch',slug:'lunch'}});
const product=await prisma.product.create({data:{tenantId:tenant.id,categoryId:category.id,name:'Rice bowl',price:1000,options:[{name:'Avocado',price:200}]}});
const otherProduct=await prisma.product.create({data:{tenantId:other.id,name:'Private product',price:900}});
const request=async(method:string,url:string,user=owner,payload?:unknown,expected=200)=>{
 const r=await app.inject({method:method as any,url,headers:{authorization:`Bearer ${app.jwt.sign({sub:user.id,type:'access'})}`,'x-tenant-id':tenant.id},...(payload===undefined?{}:{payload:payload as any})});
 assert.equal(r.statusCode,expected,`${method} ${url}: ${r.body}`);
 return r.body?r.json():null;
};
const checkout={tenantId:tenant.id,branchId:branch.id,paymentMethod:'CASH',fulfillmentType:'DELIVERY',deliveryAddress:'Kigali test address',deliveryLatitude:-1.951,deliveryLongitude:30.051,items:[{productId:product.id,quantity:1,options:['Avocado']}]};
let driver:any,driverUser:any,order:any;
try {
 await test('cent allocation never creates negative item totals',async()=>{
  const {allocateDiscount}=await import('../apps/api/src/lib/checkout.js');
  const {Prisma}=await import('../packages/database/src/client.js');
  const parts=allocateDiscount(new Prisma.Decimal('0.02'),Array.from({length:5},()=>new Prisma.Decimal('0.01')));
  assert.equal(parts.reduce((s,v)=>s.plus(v),new Prisma.Decimal(0)).toString(),'0.02');
  assert.ok(parts.every(v=>v.gte(0)&&v.lte('0.01')));
 });
 await test('public marketplace lists merchants and opens their catalog with active delivery zones',async()=>{
  await prisma.deliveryZone.create({data:{branchId:branch.id,minDistanceKm:10,maxDistanceKm:20,fee:900,isActive:false}});
  const listed=await app.inject({method:'GET',url:'/v1/marketplace/merchants'});
  assert.equal(listed.statusCode,200,listed.body);
  assert.deepEqual(listed.json().map((m:any)=>m.id),[tenant.id]);
  assert.equal(listed.json()[0].branches[0].deliveryZones.length,1);
  const catalog=await app.inject({method:'GET',url:`/v1/marketplace/merchants/${tenant.slug}`});
  assert.equal(catalog.statusCode,200,catalog.body);
  assert.equal(catalog.json().categories[0].products[0].id,product.id);
  assert.equal(catalog.json().branches[0].deliveryZones.length,1);
  const search=await app.inject({method:'GET',url:'/v1/marketplace/merchants?q=Rice'});
  assert.equal(search.statusCode,200,search.body);
  assert.equal(search.json()[0].id,tenant.id);
 });
 await test('tenant isolation and staff write restrictions',async()=>{
  await request('PATCH',`/v1/merchant/products/${otherProduct.id}`,owner,{price:1},404);
  await request('PATCH',`/v1/merchant/products/${product.id}`,outsider,{price:1},403);
  await request('PATCH',`/v1/merchant/products/${product.id}`,staff,{price:1},403);
  await request('PATCH',`/v1/merchant/products/${product.id}`,owner,{imageUrl:`/v1/media/${other.id}/photo.png`},400);
  await request('POST','/v1/notifications/devices',customer,{app:'merchant',token:'a'.repeat(32)},403);
 });
 await test('driver creation never exposes password hashes, enrollment is tenant scoped',async()=>{
  driver=await request('POST','/v1/merchant/drivers/create',owner,{email:'driver@example.test',phone:'+250788000004',firstName:'Aline',password:'Test-password-123',branchId:branch.id},201);
  assert.equal(JSON.stringify(driver).includes('passwordHash'),false);
  driverUser=await prisma.user.findUniqueOrThrow({where:{id:driver.user.id}});
  assert.ok(driverUser.passwordHash);assert.notEqual(driverUser.passwordHash,'Test-password-123');
  await request('PATCH',`/v1/merchant/drivers/${driver.id}/details`,owner,{maxConcurrentOrders:1,vehicleType:'BICYCLE'});
  await request('PATCH','/v1/driver/availability',driverUser,{isOnline:true,isAvailable:true});
 });
 await test('required groups and separately configured lines are priced on the server',async()=>{
  const configured=await request('POST','/v1/merchant/products',owner,{name:'Custom meal',price:1000,categoryId:category.id,options:[{name:'White rice',price:0,group:'Rice',minSelect:1,maxSelect:1},{name:'Brown rice',price:200,group:'Rice',minSelect:1,maxSelect:1},{name:'Cheese',price:100}]},201);
  await request('POST','/v1/customer/orders',customer,{...checkout,items:[{productId:configured.id,quantity:1}]},409);
  await request('POST','/v1/customer/orders',customer,{...checkout,items:[{productId:configured.id,quantity:1,options:['White rice','Brown rice']}]},409);
  const payload={...checkout,fulfillmentType:'PICKUP',deliveryInstructions:'Please include utensils.',items:[{productId:configured.id,quantity:1,options:['White rice']},{productId:configured.id,quantity:2,options:['Brown rice','Cheese']}]};
  const preview=await request('POST','/v1/customer/checkout-preview',customer,payload);
  const placed=await request('POST','/v1/customer/orders',customer,payload,201);
  assert.equal(placed.items.length,2);assert.equal(Number(placed.subtotal),3600);assert.equal(Number(placed.total),Number(preview.total));assert.equal(placed.deliveryInstructions,'Please include utensils.');
  await request('PATCH',`/v1/merchant/products/${configured.id}`,owner,{isAvailable:false});
  await request('POST','/v1/customer/orders',customer,payload,409);
  await request('PATCH',`/v1/merchant/products/${configured.id}`,owner,{options:[{name:' White rice ',price:0},{name:'White rice',price:0}]},400);
 });
 await test('operator pay controls are authorized and require valid rates',async()=>{
  await request('PATCH','/v1/merchant/driver-pay',outsider,{driverBasePay:300,driverPerKmPay:50},403);
  await request('PATCH','/v1/merchant/driver-pay',staff,{driverBasePay:300,driverPerKmPay:50},403);
  await request('PATCH','/v1/merchant/driver-pay',owner,{driverBasePay:-1,driverPerKmPay:50},400);
  await request('PATCH','/v1/merchant/driver-pay',owner,{driverBasePay:300,driverPerKmPay:50});
 });
 await test('checkout blocks suspended categories, closed branches, unavailable payments and invalid options',async()=>{
  await request('PATCH',`/v1/merchant/categories/${category.id}`,owner,{isActive:false});
  await request('POST','/v1/customer/orders',customer,checkout,409);
  await request('PATCH',`/v1/merchant/categories/${category.id}`,owner,{isActive:true});
  await request('PATCH',`/v1/merchant/branches/${branch.id}/hours`,owner,{closedUntil:new Date(Date.now()+3600000).toISOString()});
  await request('POST','/v1/customer/orders',customer,checkout,409);
  await request('PATCH',`/v1/merchant/branches/${branch.id}/hours`,owner,{closedUntil:null});
  await request('POST','/v1/customer/orders',customer,{...checkout,paymentMethod:'CARD'},409);
  await request('POST','/v1/customer/orders',customer,{...checkout,items:[{productId:product.id,quantity:1,options:['Unknown']}]},409);
  await request('POST','/v1/customer/orders',customer,{...checkout,items:[{productId:product.id,quantity:1.5}]},400);
 });
 await test('server prices options, limits promotions and makes checkout retry idempotent',async()=>{
  await prisma.promotion.create({data:{tenantId:tenant.id,code:'ONCE',percent:10,maxDiscount:500,maxUses:1,expiresAt:new Date(Date.now()+86400000)}});
  const body={...checkout,promoCode:'ONCE',checkoutKey:'test-checkout-idempotency-001'};
  const preview=await request('POST','/v1/customer/checkout-preview',customer,{...body,latitude:-1.951,longitude:30.051});
  order=await request('POST','/v1/customer/orders',customer,body,201);
  assert.equal(Number(order.subtotal),1200);assert.equal(Number(order.discount),120);assert.equal(Number(order.tax),108);assert.equal(Number(order.total),1688);assert.equal(Number(preview.total),1688);
  const retried=await request('POST','/v1/customer/orders',customer,body);assert.equal(retried.id,order.id);
  await request('POST','/v1/customer/orders',customer,{...checkout,promoCode:'ONCE'},409);
  assert.equal(await prisma.promotion.findUniqueOrThrow({where:{tenantId_code:{tenantId:tenant.id,code:'ONCE'}}}).then(p=>p.usedCount),1);
  assert.match(order.deliveryPin,/^\d{4}$/);
 });
 await test('delivery capacity, customer-only PIN, transition guards and completion ledger',async()=>{
  for(const status of ['ACCEPTED','PREPARING','READY_FOR_PICKUP'])await request('PATCH',`/v1/merchant/orders/${order.id}/status`,owner,{status});
  const merchantOrders=await request('GET','/v1/merchant/orders');assert.equal(JSON.stringify(merchantOrders).includes('deliveryPin'),false);
  const offers=await request('GET','/v1/driver/deliveries/available',driverUser);assert.ok(Number(offers.find((d:any)=>d.id===order.delivery.id).estimatedPayout)>=300);
  const claimed=await request('POST',`/v1/driver/deliveries/${order.delivery.id}/claim`,driverUser,{});assert.equal(JSON.stringify(claimed).includes('deliveryPin'),false);
  const agreedPay=Number(claimed.estimatedPayout);assert.ok(agreedPay>=300);
  await request('PATCH','/v1/merchant/driver-pay',owner,{driverBasePay:900,driverPerKmPay:0});
  assert.equal(Number((await prisma.delivery.findUniqueOrThrow({where:{id:claimed.id}})).estimatedPayout),agreedPay);
  await request('PATCH','/v1/driver/location',driverUser,{latitude:-1.952,longitude:30.052});
  const tracking=await request('GET',`/v1/customer/orders/${order.id}`,customer);assert.equal(tracking.delivery.driver.latitude,-1.952);assert.ok(tracking.branch.latitude);
  await request('GET',`/v1/customer/orders/${order.id}`,outsider,undefined,404);
  await request('PATCH',`/v1/merchant/drivers/${driver.id}`,owner,{isActive:false},409);
  const second=await request('POST','/v1/customer/orders',customer,checkout,201);
  for(const status of ['ACCEPTED','PREPARING','READY_FOR_PICKUP'])await request('PATCH',`/v1/merchant/orders/${second.id}/status`,owner,{status});
  await request('POST',`/v1/driver/deliveries/${second.delivery.id}/claim`,driverUser,{},409);
  for(const status of ['AT_PICKUP','PICKED_UP','AT_DROPOFF'])await request('PATCH',`/v1/driver/deliveries/${order.delivery.id}/status`,driverUser,{status});
  await request('PATCH',`/v1/driver/deliveries/${order.delivery.id}/status`,driverUser,{status:'DELIVERED',pin:'wrong'},400);
  await request('PATCH',`/v1/driver/deliveries/${order.delivery.id}/status`,driverUser,{status:'DELIVERED',pin:order.deliveryPin});
  await request('PATCH',`/v1/driver/deliveries/${order.delivery.id}/status`,driverUser,{status:'DELIVERED',pin:order.deliveryPin},409);
  const completed=await prisma.order.findUniqueOrThrow({where:{id:order.id}});assert.equal(completed.status,'COMPLETED');assert.equal(completed.paymentStatus,'PAID');
  assert.equal(await prisma.financeEntry.count({where:{orderId:order.id,kind:'COMMISSION_DUE'}}),1);
  assert.ok(await prisma.notificationEvent.count({where:{orderId:order.id}})>=5);
 });
 await test('receipts and commission invoices are automatic, stable and tenant scoped',async()=>{
  assert.equal(await prisma.businessDocument.count({where:{orderId:order.id}}),2);
  const receipt=await request('GET',`/v1/customer/orders/${order.id}/receipt`,customer);
  assert.equal(Number(receipt.payload.total),Number(order.total));assert.equal(receipt.payload.lines[0].description,order.items[0].productName);
  const retry=await request('GET',`/v1/customer/orders/${order.id}/receipt`,customer);assert.deepEqual(retry,receipt);
  await request('GET',`/v1/customer/orders/${order.id}/receipt`,outsider,undefined,404);
  await request('GET','/v1/merchant/documents',staff,undefined,403);
  const invoices=await request('GET','/v1/merchant/documents');assert.equal(invoices[0].kind,'COMMISSION_INVOICE');assert.equal(Number(invoices[0].payload.total),Number(order.platformCommissionAmount));
  const finished=await request('GET',`/v1/customer/orders/${order.id}`,customer);assert.equal(finished.delivery.driver.latitude,null);assert.equal(finished.delivery.driver.longitude,null);
  const earnings=await request('GET','/v1/driver/earnings',driverUser);assert.equal(earnings.length,1);assert.ok(Number(earnings[0].estimatedPayout)>=300);
 });
 await test('refund access, approval and receipt requirement',async()=>{
  const refund=await request('POST',`/v1/customer/orders/${order.id}/refund`,customer,{reason:'Missing food'});
  await request('PATCH',`/v1/admin/business/refunds/${refund.id}`,owner,{status:'APPROVED',resolution:'Checked'},403);
  await request('PATCH',`/v1/admin/business/refunds/${refund.id}`,admin,{status:'REFUNDED',resolution:'Checked'},409);
  await request('PATCH',`/v1/admin/business/refunds/${refund.id}`,admin,{status:'APPROVED',resolution:'Checked'});
  await request('PATCH',`/v1/admin/business/refunds/${refund.id}`,admin,{status:'REFUNDED',resolution:'Cash returned',externalReference:'test-cash-receipt'});
  const result=await prisma.order.findUniqueOrThrow({where:{id:order.id}});assert.equal(result.paymentStatus,'REFUNDED');
  assert.equal(await prisma.financeEntry.count({where:{orderId:order.id,kind:'COMMISSION_REVERSAL'}}),1);
  assert.equal(await prisma.businessDocument.count({where:{orderId:order.id}}),4);
  const refundedReceipt=await request('GET',`/v1/customer/orders/${order.id}/receipt`,customer);assert.equal(refundedReceipt.creditNotes.length,1);assert.equal(Number(refundedReceipt.creditNotes[0].payload.total),-Number(order.total));
 });
 await test('payment verification rejects tampering and duplicate notifications do not double book',async()=>{
  await prisma.tenant.update({where:{id:tenant.id},data:{paymentSubaccount:'RS_TESTMERCHANT123'}});
  process.env.FLUTTERWAVE_SECRET_KEY='test-key';process.env.FLUTTERWAVE_WEBHOOK_SECRET='test-webhook-secret';
  const paid=await request('POST','/v1/customer/orders',customer,{...checkout,paymentMethod:'CARD'},201);
  await prisma.paymentAttempt.create({data:{orderId:paid.id,customerId:customer.id,reference:`fida-${paid.id}`,provider:'FLUTTERWAVE'}});
  const original=globalThis.fetch;let providerAmount=1;
  globalThis.fetch=async()=>new Response(JSON.stringify({status:'success',data:{status:'successful',tx_ref:`fida-${paid.id}`,currency:'RWF',amount:providerAmount}}),{status:200});
  try{
   const webhook=(secret:string)=>app.inject({method:'POST',url:'/v1/payments/webhook',headers:{'verif-hash':secret},payload:{event:'charge.completed',data:{id:12345}}});
   assert.equal((await webhook('forged')).statusCode,401);
   assert.equal((await webhook('test-webhook-secret')).statusCode,200);
   assert.equal((await prisma.order.findUniqueOrThrow({where:{id:paid.id}})).paymentStatus,'PENDING');
   providerAmount=Number(paid.total);
   assert.equal((await webhook('test-webhook-secret')).statusCode,200);
   assert.equal((await webhook('test-webhook-secret')).statusCode,200);
   assert.equal((await prisma.order.findUniqueOrThrow({where:{id:paid.id}})).paymentStatus,'PAID');
   assert.equal(await prisma.financeEntry.count({where:{orderId:paid.id,kind:'ONLINE_PAYMENT'}}),1);
  }finally{globalThis.fetch=original;}
 });
 await test('staged merchant applications stay hidden until audited approval',async()=>{
  const application=await request('POST','/v1/merchant/applications',outsider,{},201);
  await request('PATCH',`/v1/merchant/applications/${application.id}`,owner,{stage:0,data:{legalName:'Other company',taxId:'123456789'}},404);
  const data={legalName:'New Store Ltd',taxId:'123456789',name:'Approved Store',slug:'approved-store',merchantType:'RESTAURANT',timezone:'Africa/Kigali',cuisineTags:['Local'],logoUrl:'https://images.example.test/logo.png',coverUrl:'https://images.example.test/cover.png',addressLine:'KK 31 Avenue',city:'Kigali',latitude:-1.95,longitude:30.05,openingHours:Array.from({length:7},()=>[{open:'08:00',close:'12:00'},{open:'14:00',close:'21:00'}])};
  await prisma.mediaAsset.createMany({data:[data.logoUrl,data.coverUrl].map(url=>({ownerId:outsider.id,url,bytes:100}))});
  await request('PATCH',`/v1/merchant/applications/${application.id}`,outsider,{stage:3,data},409);
  for(let stage=0;stage<4;stage++)await request('PATCH',`/v1/merchant/applications/${application.id}`,outsider,{stage,data});
  const submitted=await request('POST',`/v1/merchant/applications/${application.id}/submit`,outsider,{});
  assert.equal((await prisma.tenant.findUniqueOrThrow({where:{id:submitted.tenantId}})).status,'PENDING_APPROVAL');
  const access=app.jwt.sign({sub:outsider.id,type:'access'});
  const blocked=await app.inject({method:'GET',url:'/v1/merchant/orders',headers:{authorization:`Bearer ${access}`,'x-tenant-id':submitted.tenantId}});assert.equal(blocked.statusCode,403);
  await request('GET','/v1/marketplace/merchants/approved-store',customer,undefined,404);
  await request('POST',`/v1/admin/merchant-applications/${application.id}/review`,owner,{action:'APPROVE',reason:'Checked'},403);
  await request('POST',`/v1/admin/merchant-applications/${application.id}/review`,admin,{action:'REJECT',reason:'Correct your registration details'});
  await request('POST',`/v1/merchant/applications/${application.id}/reopen`,owner,{},409);
  await request('POST',`/v1/merchant/applications/${application.id}/reopen`,outsider,{});
  for(let stage=0;stage<4;stage++)await request('PATCH',`/v1/merchant/applications/${application.id}`,outsider,{stage,data:{...data,legalName:'Corrected Store Ltd'}});
  const resubmitted=await request('POST',`/v1/merchant/applications/${application.id}/submit`,outsider,{});
  assert.equal(resubmitted.tenantId,submitted.tenantId);
  assert.equal(await prisma.tenant.count({where:{slug:'approved-store'}}),1);
  await request('POST',`/v1/admin/merchant-applications/${application.id}/review`,admin,{action:'APPROVE',reason:'Registration and location verified'});
  await request('POST',`/v1/admin/merchant-applications/${application.id}/review`,admin,{action:'REJECT',reason:'Second review'},409);
  const enabled=await app.inject({method:'GET',url:'/v1/merchant/orders',headers:{authorization:`Bearer ${access}`,'x-tenant-id':submitted.tenantId}});assert.equal(enabled.statusCode,200);
  await request('GET','/v1/marketplace/merchants/approved-store',customer);
 });
 await test('kitchen staff are tenant scoped, stock-only, financially masked and immediately revocable',async()=>{
  const membership=await request('POST','/v1/merchant/staff',owner,{email:'kitchen@example.test',password:'Kitchen-password-123',role:'KITCHEN_CREW',firstName:'Kitchen',branchId:branch.id},201);
  const kitchen=await prisma.user.findUniqueOrThrow({where:{id:membership.user.id}});
  const queue=await request('GET','/v1/merchant/orders',kitchen);
  assert.ok(queue.length>0);
  for(const field of ['platformCommissionAmount','estimatedPayout','paymentStatus','settledPayout','totalPrice'])assert.equal(JSON.stringify(queue).includes(`"${field}"`),false);
  for(const route of ['finance','statement','driver-pay','documents','staff','driver-settlements','promotions'])await request('GET',`/v1/merchant/${route}`,kitchen,undefined,403);
  await request('PATCH',`/v1/merchant/products/${product.id}/stock`,kitchen,{isAvailable:false});
  await request('PATCH',`/v1/merchant/products/${product.id}/stock`,kitchen,{isAvailable:true,price:1},400);
  await request('PATCH',`/v1/merchant/products/${otherProduct.id}/stock`,kitchen,{isAvailable:true},404);
  await request('PATCH',`/v1/merchant/products/${product.id}`,kitchen,{price:1},403);
  await request('PATCH',`/v1/merchant/products/${product.id}/stock`,owner,{isAvailable:true});
  await request('PATCH',`/v1/merchant/staff/${membership.id}`,owner,{isActive:false});
  await request('GET','/v1/merchant/orders',kitchen,undefined,403);
 });
 await test('item promotions, cart minimum, localized tax, notes and confirmed total use one pricing engine',async()=>{
  await request('PATCH','/v1/merchant/settings',owner,{taxPercent:18,taxLabel:'VAT'});
  const item=await request('POST','/v1/merchant/products',owner,{name:'Promo meal',price:1000,categoryId:category.id},201);
  const promo={code:'ITEM100',discountType:'FLAT',flatAmount:100,productId:item.id,maxDiscount:1000,minimumOrder:0,maxUses:50,expiresAt:new Date(Date.now()+86400000).toISOString(),stackable:true};
  await request('POST','/v1/merchant/promotions',owner,{...promo,productId:otherProduct.id},400);
  await request('POST','/v1/merchant/promotions',owner,promo,201);
  await request('POST','/v1/merchant/promotions',owner,{...promo,code:'CART10',productId:null,discountType:'PERCENT',percent:10,minimumOrder:1500},201);
  const payload={...checkout,items:[{productId:item.id,quantity:2}],promoCode:'CART10',cooking_instructions:'No chilli please'};
  const totals=await request('POST','/v1/customer/checkout-preview',customer,payload);
  assert.equal(Number(totals.itemDiscount),200);assert.equal(Number(totals.cartDiscount),180);assert.equal(Number(totals.tax),291.6);assert.equal(Number(totals.total),2411.6);
  await request('POST','/v1/customer/orders',customer,{...payload,confirmedTotal:2400},409);
  const placed=await request('POST','/v1/customer/orders',customer,{...payload,confirmedTotal:2411.6},201);
  assert.equal(placed.cookingInstructions,'No chilli please');assert.equal(Number(placed.items[0].tax),291.6);
  await request('POST','/v1/customer/checkout-preview',customer,{...payload,items:[{productId:item.id,quantity:1}]},409);
  await request('PATCH','/v1/admin/promotion-policy',admin,{maxPercent:40,maxDiscount:5000,allowStacking:false});
  await request('POST','/v1/customer/checkout-preview',customer,payload,409);
  await request('PATCH','/v1/admin/promotion-policy',admin,{maxPercent:100,maxDiscount:100000000,allowStacking:true});
 });
 await test('driver settlement records use actual operator payments, never current rates as history',async()=>{
  const delivery=await prisma.delivery.findUniqueOrThrow({where:{orderId:order.id}});
  await prisma.delivery.update({where:{id:delivery.id},data:{estimatedPayout:null}});
  await request('POST',`/v1/merchant/driver-settlements/${delivery.id}`,outsider,{amount:1200,reference:'payment-proof-1'},403);
  await request('POST',`/v1/merchant/driver-settlements/${delivery.id}`,owner,{amount:1200,reference:'payment-proof-1'});
  const earnings=await request('GET','/v1/driver/earnings',driverUser);const record=earnings.find((r:any)=>r.id===delivery.id);
  assert.equal(record.estimatedPayout,null);assert.equal(Number(record.settledPayout),1200);
  await request('POST',`/v1/merchant/driver-settlements/${delivery.id}`,owner,{amount:900,reference:'payment-proof-2'},409);
 });

 await test('online checkout routes to the merchant with no upfront platform commission',async()=>{
  process.env.FLUTTERWAVE_SECRET_KEY='test-only';process.env.FLUTTERWAVE_WEBHOOK_SECRET='test-webhook';
  const originalFetch=globalThis.fetch;let payload:any;
  globalThis.fetch=async(_input,options)=>{payload=JSON.parse(String(options?.body));return new Response(JSON.stringify({status:'success',data:{link:'https://checkout.example.test/pay'}}),{status:200});};
  try {
   await request('PATCH',`/v1/admin/business/tenants/${tenant.id}/payment-routing`,owner,{paymentSubaccount:'RS_WRONG'},403);
   await request('PATCH',`/v1/admin/business/tenants/${tenant.id}/payment-routing`,admin,{paymentSubaccount:'RS_TESTMERCHANT123'});
   const placed=await request('POST','/v1/customer/orders',customer,{...checkout,fulfillmentType:'PICKUP',paymentMethod:'CARD'},201);
   await request('POST',`/v1/customer/orders/${placed.id}/payment`,customer,{});
   assert.deepEqual(payload.subaccounts,[{id:'RS_TESTMERCHANT123',transaction_charge_type:'flat',transaction_charge:0}]);
   await prisma.order.update({where:{id:placed.id},data:{paymentStatus:'PAID'}});
   for(const status of ['ACCEPTED','PREPARING','READY_FOR_PICKUP','COMPLETED'])await request('PATCH',`/v1/merchant/orders/${placed.id}/status`,owner,{status});
   assert.equal(await prisma.financeEntry.count({where:{orderId:placed.id,kind:'MERCHANT_PAYABLE'}}),0);
   assert.equal(await prisma.businessDocument.count({where:{orderId:placed.id,kind:'COMMISSION_INVOICE'}}),1);
   await request('GET','/v1/admin/business/commission-balances',owner,undefined,403);
   const balances=await request('GET','/v1/admin/business/commission-balances',admin);assert.ok(Number(balances.find((t:any)=>t.id===tenant.id).outstanding)>0);
  }finally{globalThis.fetch=originalFetch;}
 });

 await test('binary branding is authenticated, decoded, owned and cannot select a server path',async()=>{
  const sharp=(await import('../apps/api/node_modules/sharp/lib/index.js')).default;
  const png=await sharp({create:{width:4,height:4,channels:3,background:'#07885a'}}).png().toBuffer();
  const upload=await app.inject({method:'POST',url:'/v1/merchant/branding',headers:{authorization:`Bearer ${app.jwt.sign({sub:owner.id,type:'access'})}`,'content-type':'image/png'},payload:png});
  assert.equal(upload.statusCode,201,upload.body);const asset=upload.json();
  assert.match(asset.url,/^\/v1\/media\/branding_.*\.webp$/);
  assert.equal((await prisma.mediaAsset.findUniqueOrThrow({where:{url:asset.url}})).ownerId,owner.id);
  const stored=await app.inject({method:'GET',url:asset.url});assert.equal(stored.statusCode,200);assert.match(stored.headers['content-type']!,/image\/webp/);
  const guard=join(media,'guard.txt');await writeFile(guard,'Do not touch');
  await request('POST','/v1/merchant/branding',owner,{path:guard,size:12},400);
  assert.equal(await readFile(guard,'utf8'),'Do not touch');
  const invalid=await app.inject({method:'POST',url:'/v1/merchant/branding',headers:{authorization:`Bearer ${app.jwt.sign({sub:owner.id,type:'access'})}`,'content-type':'image/png'},payload:Buffer.from('<svg></svg>')});assert.equal(invalid.statusCode,400);
  const unauth=await app.inject({method:'POST',url:'/v1/merchant/branding',headers:{'content-type':'image/png'},payload:png});assert.equal(unauth.statusCode,401);
  const oversized=await app.inject({method:'POST',url:'/v1/merchant/branding',headers:{authorization:`Bearer ${app.jwt.sign({sub:owner.id,type:'access'})}`,'content-type':'image/png'},payload:Buffer.alloc(5*1024*1024+1)});assert.equal(oversized.statusCode,413);
  const application=await request('POST','/v1/merchant/applications',customer,{},201);
  await request('PATCH',`/v1/merchant/applications/${application.id}`,customer,{stage:0,data:{legalName:'Customer business',taxId:'123456'}});
  await request('PATCH',`/v1/merchant/applications/${application.id}`,customer,{stage:1,data:{name:'Café & Grill',merchantType:'RESTAURANT',timezone:'UTC',cuisineTags:['Local'],logoUrl:asset.url,coverUrl:asset.url}},400);
  const {storeSlug}=await import('../apps/api/src/lib/merchant-application.js');assert.equal(storeSlug(' Café & Grill! '),'cafe-grill');
  await request('PATCH','/v1/merchant/store',owner,{name:'Renamed Kitchen',legalName:'Kitchen Ltd',taxId:'123456',merchantType:'RESTAURANT',timezone:'UTC',cuisineTags:['Local'],logoUrl:asset.url,coverUrl:asset.url});
  assert.equal((await prisma.tenant.findUniqueOrThrow({where:{id:tenant.id}})).slug,tenant.slug);
  await request('PATCH',`/v1/merchant/store/branches/${branch.id}`,owner,{city:'Kigali',latitude:-1.95,longitude:30.05});
  await request('PATCH',`/v1/merchant/store/branches/${branch.id}`,owner,{isActive:false},409);
 });
 await test('favorites accept JSON and address deletion promotes the remaining default',async()=>{
  await request('PUT',`/v1/customer/favorites/${tenant.id}`,customer,{});
  assert.equal((await request('GET','/v1/customer/favorites',customer)).some((m:any)=>m.id===tenant.id),true);
  await request('DELETE',`/v1/customer/favorites/${tenant.id}`,customer,{},204);
  const first=await request('POST','/v1/customer/addresses',customer,{addressLine:'First Kigali address'},201);
  const second=await request('POST','/v1/customer/addresses',customer,{addressLine:'Second Kigali address'},201);
  await request('DELETE',`/v1/customer/addresses/${first.id}`,outsider,{},404);
  await request('DELETE',`/v1/customer/addresses/${first.id}`,customer,{},204);
  assert.equal((await prisma.customerAddress.findUniqueOrThrow({where:{id:second.id}})).isDefault,true);
  await request('DELETE',`/v1/customer/addresses/${first.id}`,customer,{},404);
  await request('POST',`/v1/customer/recent-stores/${tenant.id}`,customer,{});
  assert.equal((await request('GET','/v1/customer/recent-stores',customer))[0].tenantId,tenant.id);
 });
 await test('managers may manage branch staff but never owners, managers or other branches',async()=>{
  const manager=await request('POST','/v1/merchant/staff',owner,{email:'manager09@example.test',password:'Manager-test-password-123',role:'MANAGER',branchId:branch.id},201);
  const user=await prisma.user.findUniqueOrThrow({where:{id:manager.user.id}});
  const otherBranch=await prisma.branch.create({data:{tenantId:tenant.id,name:'East'}});
  await request('POST','/v1/merchant/staff',user,{email:'invalid09@example.test',password:'Staff-test-password-123',role:'STAFF',branchId:otherBranch.id},403);
  const member=await request('POST','/v1/merchant/staff',user,{email:'staff09@example.test',password:'Staff-test-password-123',role:'STAFF',branchId:branch.id},201);
  await request('PATCH',`/v1/merchant/staff/${member.id}`,user,{firstName:'Edited',isActive:false});
  await request('PATCH',`/v1/merchant/staff/${member.id}`,user,{role:'MANAGER'},400);
  await request('PATCH',`/v1/merchant/staff/${member.id}`,user,{branchId:otherBranch.id},403);
  await request('DELETE',`/v1/merchant/staff/${manager.id}`,user,{},404);
  await request('PATCH',`/v1/merchant/staff/${member.id}`,owner,{branchId:otherBranch.id});
  await request('DELETE',`/v1/merchant/staff/${member.id}`,user,{},404);
  await request('DELETE',`/v1/merchant/staff/${member.id}`,owner,{},204);
  await request('GET','/v1/merchant/store',user,undefined,403);
 });
 const password='Admin-test-password-123';
 const {hashPassword}=await import('../apps/api/src/lib/security.js');
 await prisma.user.update({where:{id:admin.id},data:{passwordHash:await hashPassword(password)}});
 await test('period invoices are idempotent summaries without additional ledger charges',async()=>{
  const date=new Date().toISOString().slice(0,10),body={tenantId:tenant.id,from:date,to:date};
  const count=await prisma.financeEntry.count();
  await request('POST','/v1/admin/commission-periods',owner,body,403);
  const invoice=await request('POST','/v1/admin/commission-periods',admin,body);
  const again=await request('POST','/v1/admin/commission-periods',admin,body);assert.equal(again.id,invoice.id);
  assert.equal(await prisma.financeEntry.count(),count);
  const documents=await prisma.businessDocument.findMany({where:{id:{in:invoice.payload.documentIds}}});
  const {Prisma}=await import('../packages/database/src/client.js');
  assert.equal(invoice.payload.total,documents.reduce((s,d)=>s.plus((d.payload as any).total),new Prisma.Decimal(0)).toFixed(2));
  await request('POST','/v1/admin/commission-periods',admin,{...body,from:'2026-02-30'},400);
 });
 await test('root controls require reauthentication, protect administrators and validate preview freshness',async()=>{
  await request('GET','/v1/admin/system/collections',owner,undefined,403);
  const collections=await request('GET','/v1/admin/system/collections',admin);assert.ok(collections.some((c:any)=>c.name==='Product'));
  await request('PATCH','/v1/admin/system/settings',admin,{password:'wrong',values:{}},403);
  await request('PATCH','/v1/admin/system/settings',admin,{password,values:{ADMIN_ALLOWED_IPS:'192.0.2.1'}},400);
  await request('PATCH','/v1/admin/system/settings',admin,{password,values:{PUBLIC_BASE_URL:'http://unsafe.test'}},400);
  await request('PATCH','/v1/admin/system/settings',admin,{password,values:{FEATURED_STORE_IDS:tenant.id,MAINTENANCE_MODE:'false'}});
  const feed=await request('GET','/v1/marketplace/merchants',customer);assert.equal(feed.find((m:any)=>m.id===tenant.id).featured,true);
  await request('PATCH','/v1/admin/system/data/User',admin,{password,reason:'Test own account protection',key:{id:admin.id},changes:{isActive:false}},409);
  await request('POST','/v1/admin/system/actions/preview',admin,{password,reason:'Test own account protection',kind:'DELETE',model:'User',key:{id:admin.id}},409);
  const victim=await prisma.tenant.create({data:{name:'Delete test',slug:'delete-test',merchantType:'OTHER'}});
  const child=await prisma.product.create({data:{tenantId:victim.id,name:'Delete child',price:500}});
  const previewBody={password,reason:'Isolated database cascade test',kind:'DELETE',model:'Tenant',key:{id:victim.id}};
  const first=await request('POST','/v1/admin/system/actions/preview',admin,previewBody);assert.equal(first.counts.Product,1);
  await prisma.product.update({where:{id:child.id},data:{price:600}});
  await request('POST','/v1/admin/system/actions/execute',admin,{password,token:first.token,confirmation:first.confirmation},409);
  const current=await request('POST','/v1/admin/system/actions/preview',admin,previewBody);
  await request('POST','/v1/admin/system/actions/execute',admin,{password,token:current.token,confirmation:'wrong'},400);
  await request('POST','/v1/admin/system/actions/execute',admin,{password,token:current.token,confirmation:current.confirmation});
  assert.equal(await prisma.tenant.count({where:{id:victim.id}}),0);assert.equal(await prisma.product.count({where:{id:child.id}}),0);
  await request('POST','/v1/admin/system/actions/execute',admin,{password,token:current.token,confirmation:current.confirmation},409);
 });
 await test('protected reset clears only isolated operational data while preserving admin, settings, audit and schemas',async()=>{
  const preview=await request('POST','/v1/admin/system/actions/preview',admin,{password,reason:'Isolated PGlite reset verification',kind:'RESET'});
  assert.ok(preview.counts.Order>0);
  await request('POST','/v1/admin/system/actions/execute',admin,{password,token:preview.token,confirmation:preview.confirmation});
  assert.equal(await prisma.order.count(),0);assert.equal(await prisma.tenant.count(),0);
  assert.equal(await prisma.user.count({where:{isPlatformAdmin:false}}),0);
  assert.equal(await prisma.user.count({where:{id:admin.id,isPlatformAdmin:true}}),1);
  assert.equal(await prisma.runtimeSettings.count(),1);
  assert.ok(await prisma.adminAuditEvent.count({where:{action:'OPERATIONAL_RESET'}}));
  const {models,delegate}=await import('../apps/api/src/lib/admin-data.js');for(const model of models)await delegate(prisma,model.name).count();
 });

} finally {
 await app.close();await prisma.$disconnect();await socket.stop();await db.close();await rm(media,{recursive:true,force:true});
}
