'use client';
import {useEffect,useState} from 'react';
type Store={id:string;name:string;slug:string};
export function FeaturedStores({value,mode,onChange}:{value:string;mode:string;onChange:(ids:string,mode:string)=>void}){
 const ids=value.split(',').filter(Boolean),[query,setQuery]=useState(''),[results,setResults]=useState<Store[]>([]),[selected,setSelected]=useState<Store[]>([]),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();const timer=setTimeout(async()=>{try{const r=await fetch(`/api/admin/system/stores?q=${encodeURIComponent(query)}`,{signal:controller.signal});if(!r.ok)throw Error('Unable to search stores.');setResults(await r.json());setError('');}catch(e){if(!controller.signal.aborted)setError(String(e));}},250);return()=>{clearTimeout(timer);controller.abort();};},[query]);
 useEffect(()=>{if(!value){setSelected([]);return;}const controller=new AbortController();fetch(`/api/admin/system/stores?ids=${encodeURIComponent(value)}`,{signal:controller.signal}).then(async r=>{if(!r.ok)throw Error('Unable to load selected stores.');setSelected(await r.json());}).catch(e=>{if(!controller.signal.aborted)setError(String(e));});return()=>controller.abort();},[value]);
 return <fieldset><legend>Featured stores</legend><label>Selection mode<select value={mode||'AUTO'} onChange={e=>onChange(value,e.target.value)}><option value="AUTO">Automatic · best sellers over 30 days</option><option value="MANUAL">Administrator selection</option></select></label>{mode==='MANUAL'&&<><label>Find active stores<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search store name"/></label><div aria-label="Selected featured stores">{ids.map(id=><button type="button" className="mp-secondary" key={id} onClick={()=>onChange(ids.filter(v=>v!==id).join(','),'MANUAL')}>{selected.find(s=>s.id===id)?.name||id} ×</button>)}</div><div role="group" aria-label="Matching active stores" style={{maxHeight:240,overflowY:'auto'}}>{results.map(store=><label key={store.id} style={{display:'flex',gap:8,alignItems:'center'}}><input type="checkbox" checked={ids.includes(store.id)} disabled={!ids.includes(store.id)&&ids.length>=12} onChange={e=>onChange((e.target.checked?[...ids,store.id]:ids.filter(v=>v!==store.id)).join(','),'MANUAL')}/>{store.name} <small>{store.slug}</small></label>)}</div><small>{ids.length}/12 selected</small></>}{error&&<p role="alert">{error}</p>}</fieldset>;
}
