'use client';
import {useEffect,useState} from 'react';
import '../merchant/merchant.css';
import {FeaturedStores} from './featured-stores';
import {DocumentView} from '../merchant/document-view';
type Row=Record<string,any>;
async function call(path:string,method='GET',body?:unknown){const r=await fetch(`/api/admin/${path}`,{method,headers:{'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});const data=await r.json();if(!r.ok)throw Error(data.message||data.error);return data;}
export default function SystemPage(){
 const [tab,setTab]=useState('Collections'),[collections,setCollections]=useState<Row[]>([]),[model,setModel]=useState('Tenant'),[rows,setRows]=useState<Row[]>([]),[count,setCount]=useState(0),[offset,setOffset]=useState(0),[settings,setSettings]=useState<Row>({}),[ip,setIp]=useState(''),[invoiceData,setInvoiceData]=useState<Row>({tenants:[],invoices:[]}),[document,setDocument]=useState<Row|null>(null),[edit,setEdit]=useState<Row|null>(null),[preview,setPreview]=useState<Row|null>(null),[password,setPassword]=useState(''),[reason,setReason]=useState(''),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const schema=collections.find(m=>m.name===model);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(String(e));}finally{setBusy(false);}};
 const load=async()=>{if(tab==='Collections'){const result=await call(`system/data/${model}?offset=${offset}`);setRows(result.rows);setCount(result.count);}if(tab==='Settings'){const result=await call('system/settings');setSettings(result.values);setIp(result.connectionIp);}if(tab==='Commission invoices')setInvoiceData(await call('commission-periods'));};
 useEffect(()=>{call('system/collections').then(setCollections).catch(e=>setError(String(e)));},[]);
 useEffect(()=>{void run(load);},[tab,model,offset]);
 const security=<div className="mp-form-grid"><label>Current administrator password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Audit reason<input minLength={5} value={reason} onChange={e=>setReason(e.target.value)}/></label></div>;
 const requestDelete=(row:Row)=>void run(async()=>{setPreview(await call('system/actions/preview','POST',{kind:'DELETE',model,key:Object.fromEntries(schema!.keys.map((k:string)=>[k,row[k]])),password,reason}));setConfirmation('');});
 return <main className="mp control-page"><header className="control-header"><div><a href="/">← Control center</a><h1>Platform administration</h1></div><a href="/audit">Audit history</a></header><nav className="control-tabs" aria-label="System modules">{['Collections','Commission invoices','Settings','System reset'].map(t=><button className={t===tab?'':'mp-secondary'} key={t} onClick={()=>{setTab(t);setEdit(null);setPreview(null);}}>{t}</button>)}</nav>
 {error&&<p role="alert" className="mp-error">{error}</p>}{notice&&<p role="status">{notice}</p>}{busy&&<progress aria-label="Working"/>}
 {tab==='Collections'&&<><section className="mp-panel"><div className="mp-form-grid"><label>Collection<select value={model} onChange={e=>{setModel(e.target.value);setOffset(0);setEdit(null);}}>{collections.map(m=><option key={m.name}>{m.name}</option>)}</select></label><p>{count} records · showing {count?offset+1:0}–{Math.min(offset+50,count)}</p></div>{security}<div className="table-wrap"><table className="control-table"><thead><tr><th>Record</th><th>Details</th><th>Actions</th></tr></thead><tbody>{rows.map((row,i)=><tr key={i}><td>{schema?.keys.map((key:string)=><div key={key}><small>{key}</small><br/>{String(row[key])}</div>)}</td><td>{Object.entries(row).filter(([k])=>!schema?.keys.includes(k)).slice(0,5).map(([k,v])=><div key={k}><strong>{k}: </strong>{typeof v==='object'?JSON.stringify(v):String(v)}</div>)}</td><td><div className="mp-actions"><button disabled={busy} onClick={()=>setEdit({...row})}>Edit</button><button className="mp-danger" disabled={busy||!password||reason.trim().length<5} onClick={()=>requestDelete(row)}>{model==='Tenant'?'Preview store purge':'Preview cascade delete'}</button></div></td></tr>)}</tbody></table></div><div className="mp-actions"><button disabled={offset===0||busy} onClick={()=>setOffset(Math.max(0,offset-50))}>Previous</button><button disabled={offset+50>=count||busy} onClick={()=>setOffset(offset+50)}>Next</button></div></section></>}
 {tab==='Settings'&&<form className="mp-panel" onSubmit={e=>{e.preventDefault();void run(async()=>{await call('system/settings','PATCH',{values:settings,password});setPassword('');setNotice('Settings saved. API instances reload these settings within five seconds.');});}}><h2>Master settings</h2><p>API connection address: {ip}. Configure trusted proxy addresses in the deployment environment before restricting client IPs.</p><div className="mp-form-grid">{Object.entries(settings).filter(([key])=>!['FEATURED_STORE_IDS','FEATURED_STORE_MODE'].includes(key)).map(([key,value])=><label key={key}>{key.replaceAll('_',' ')}{key==='MAINTENANCE_MODE'?<select value={value} onChange={e=>setSettings({...settings,[key]:e.target.value})}><option value="">Environment default</option><option value="false">Off</option><option value="true">On</option></select>:<input value={value} onChange={e=>setSettings({...settings,[key]:e.target.value})}/>}</label>)}</div><FeaturedStores value={settings.FEATURED_STORE_IDS||''} mode={settings.FEATURED_STORE_MODE||'AUTO'} onChange={(ids,mode)=>setSettings({...settings,FEATURED_STORE_IDS:ids,FEATURED_STORE_MODE:mode})}/>{security}<button disabled={busy||!password}>Save master settings</button><p>Access URLs use HTTPS. IP rules accept addresses or CIDRs separated by commas. Automatic featured stores use completed non-refunded orders, units sold and ratings over the recent sales period.</p></form>}
 {tab==='Commission invoices'&&<><form className="mp-panel" onSubmit={e=>{e.preventDefault();const fields=Object.fromEntries(new FormData(e.currentTarget));void run(async()=>{const result=await call('commission-periods','POST',fields);setDocument(result);setInvoiceData(await call('commission-periods'));});}}><h2>Generate a consolidated commission invoice</h2><div className="mp-form-grid"><label>Merchant<select name="tenantId" required><option value="">Choose merchant</option>{invoiceData.tenants.map((t:Row)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>From (UTC)<input type="date" name="from" required/></label><label>Through (UTC, inclusive)<input type="date" name="to" required/></label></div><button disabled={busy}>Compile period invoice</button><p>References existing commission invoices and credits. No additional ledger charge is created.</p></form><div className="control-cards">{invoiceData.invoices.map((d:Row)=><article key={d.id} className="mp-panel"><h3>{d.payload.recipient}</h3><p>{d.payload.periodFrom} – {d.payload.periodTo}</p><p>{d.payload.total} {d.payload.currency}</p><button onClick={()=>setDocument(d)}>View / Save PDF</button></article>)}</div></>}
 {tab==='System reset'&&<section className="mp-panel danger-zone"><h2>Reset operational data</h2><p>This permanently clears store, order, delivery, customer and financial records. Database schemas, platform administrator identities, runtime settings and audit history remain. Uploaded media files on disk remain.</p><p>Create a verified database backup before proceeding.</p>{security}<button className="mp-danger" disabled={busy||!password||reason.trim().length<5} onClick={()=>void run(async()=>{setPreview(await call('system/actions/preview','POST',{kind:'RESET',password,reason}));setConfirmation('');})}>Preview RESET</button></section>}
 {edit&&schema&&<div className="mp-overlay"><form className="mp-dialog" onSubmit={e=>{e.preventDefault();const values=new FormData(e.currentTarget),changes:Row={};try{for(const field of schema.fields){if(field.readOnly)continue;const raw=values.get(field.name);if(raw===null)continue;changes[field.name]=raw===''&&field.nullable?null:field.type==='Boolean'?raw==='true':field.isList||field.list||field.type==='Json'?JSON.parse(String(raw)):['Int','Float'].includes(field.type)?Number(raw):raw;}}catch{setError('Invalid JSON field.');return;}void run(async()=>{await call(`system/data/${model}`,'PATCH',{key:Object.fromEntries(schema.keys.map((k:string)=>[k,edit[k]])),changes,password,reason});setEdit(null);setPassword('');await load();});}}><h2>Edit {model}</h2>{schema.fields.map((field:Row)=>!field.readOnly&&<label key={field.name}>{field.name}{field.enumValues?<select name={field.name} defaultValue={edit[field.name]??''}>{field.nullable&&<option value="">None</option>}{field.enumValues.map((v:string)=><option key={v}>{v}</option>)}</select>:field.type==='Boolean'?<select name={field.name} defaultValue={String(edit[field.name])}><option>true</option><option>false</option></select>:field.type==='Json'||field.list?<textarea name={field.name} rows={5} defaultValue={JSON.stringify(edit[field.name],null,2)}/>:<input name={field.name} defaultValue={edit[field.name]??''}/>}</label>)}{security}<div className="mp-actions"><button disabled={busy||!password||reason.trim().length<5}>Save changes</button><button type="button" className="mp-secondary" onClick={()=>setEdit(null)}>Cancel</button></div></form></div>}
 {preview&&<div className="mp-overlay"><section className="mp-dialog" role="dialog" aria-modal="true" aria-label="Confirm destructive action"><h2>Review affected records</h2><table className="control-table"><tbody>{Object.entries(preview.counts).map(([model,count])=><tr key={model}><th>{model}</th><td>{String(count)}</td></tr>)}</tbody></table><p>Type <strong>{preview.confirmation}</strong> to confirm. Preview expires after five minutes.</p><input aria-label="Confirmation phrase" value={confirmation} onChange={e=>setConfirmation(e.target.value)}/>{security}<div className="mp-actions"><button className="mp-danger" disabled={busy||confirmation!==preview.confirmation||!password} onClick={()=>void run(async()=>{await call('system/actions/execute','POST',{token:preview.token,confirmation,password});setPreview(null);setPassword('');setNotice('Operation completed and recorded in audit history.');await load();})}>Execute confirmed action</button><button className="mp-secondary" onClick={()=>setPreview(null)}>Cancel</button></div></section></div>}
 {document&&<DocumentView document={document} onClose={()=>setDocument(null)}/>}
 </main>;
}
