'use client';
import {useEffect,useState} from 'react';
type Row=Record<string,any>;
type Call=(path:string,method?:string,body?:unknown)=>Promise<any>;
export function BusinessSettings({tenant,branches,call,onSaved}:{tenant:Row;branches:Row[];call:Call;onSaved:()=>Promise<void>}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[pay,setPay]=useState<Row>({});
 useEffect(()=>{let active=true;call('driver-pay').then(p=>{if(active)setPay(p||{});}).catch(e=>{if(active)setError(String(e));});return()=>{active=false;};},[call]);
 const save=async(path:string,body:Row,method='PATCH')=>{setBusy(true);setError('');try{await call(path,method,body);await onSaved();}catch(e){setError(String(e));}finally{setBusy(false);}};
 return <>{error&&<p role="alert" className="mp-error">{error}</p>}<div className="mp-form-grid"><form className="mp-panel" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save('settings',{name:f.get('name'),minimumOrder:Number(f.get('minimumOrder')),timezone:f.get('timezone')});}}><h2>Store settings</h2><label>Business name<input name="name" defaultValue={tenant.name} required/></label><label>Minimum order ({tenant.currency})<input name="minimumOrder" type="number" min="0" step="0.01" defaultValue={tenant.minimumOrder} required/></label><label>Time zone<select name="timezone" defaultValue={tenant.timezone||'Africa/Kigali'}>{['Africa/Kigali','Africa/Kampala','Africa/Nairobi','Africa/Dar_es_Salaam','Africa/Bujumbura','Africa/Lubumbashi','UTC'].map(v=><option key={v}>{v}</option>)}</select></label><button disabled={busy}>Save store settings</button></form>
 <form className="mp-panel" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save('driver-pay',{driverBasePay:Number(f.get('base')),driverPerKmPay:Number(f.get('km'))});}}><h2>Driver pay estimates</h2><p>For future accepted deliveries. Uses delivery distance, excluding pickup travel and tips.</p><label>Base per delivery ({tenant.currency})<input name="base" type="number" step="0.01" min="0" required value={pay.driverBasePay??''} onChange={e=>setPay({...pay,driverBasePay:e.target.value})}/></label><label>Per kilometre ({tenant.currency})<input name="km" type="number" step="0.01" min="0" required value={pay.driverPerKmPay??''} onChange={e=>setPay({...pay,driverPerKmPay:e.target.value})}/></label><button disabled={busy}>Save pay rates</button></form></div>
 {branches.map(b=><BranchSettings key={b.id} branch={b} save={save} busy={busy} currency={tenant.currency}/>)}</>;
}
function BranchSettings({branch:b,save,busy,currency}:{branch:Row;save:(path:string,body:Row,method?:string)=>Promise<void>;busy:boolean;currency:string}){
 const [zones,setZones]=useState<Row[]>((b.deliveryZones||[]).filter((z:Row)=>z.isActive));
 useEffect(()=>setZones((b.deliveryZones||[]).filter((z:Row)=>z.isActive)),[b]);
 return <section className="mp-panel"><h2>{b.name} · Location & delivery</h2><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save(`branches/${b.id}/fulfillment`,{addressLine:f.get('addressLine'),city:f.get('city'),latitude:f.get('latitude')===''?null:Number(f.get('latitude')),longitude:f.get('longitude')===''?null:Number(f.get('longitude')),logisticsMode:f.get('logisticsMode')});}}><div className="mp-form-grid"><label>Address<input name="addressLine" defaultValue={b.addressLine||''}/></label><label>City<input name="city" defaultValue={b.city||''}/></label><label>Latitude<input type="number" step="any" min="-90" max="90" name="latitude" defaultValue={b.latitude??''}/></label><label>Longitude<input type="number" step="any" min="-180" max="180" name="longitude" defaultValue={b.longitude??''}/></label><label>Delivery team<select name="logisticsMode" defaultValue={b.logisticsMode}><option value="MERCHANT">My drivers</option><option value="FIDA">Fida fleet</option><option value="HYBRID">My drivers and Fida fleet</option></select></label></div><button disabled={busy}>Save branch details</button></form><hr/><form onSubmit={e=>{e.preventDefault();void save(`branches/${b.id}/delivery-zones`,{zones:zones.map(z=>({minDistanceKm:Number(z.minDistanceKm),maxDistanceKm:Number(z.maxDistanceKm),fee:Number(z.fee)}))},'PUT');}}><h3>Delivery distance bands</h3><p>Set each range's fee; use 0 for free delivery. Ranges must not overlap.</p>{zones.map((z,i)=><div className="mp-form-grid mp-option" key={i}>{[['minDistanceKm','From (km)'],['maxDistanceKm','To (km)'],['fee',`Fee (${currency})`]].map(([key,title])=><label key={key}>{title}<input type="number" step="0.01" min="0" required value={z[key]} onChange={e=>setZones(zones.map((v,j)=>i===j?{...v,[key]:e.target.value}:v))}/></label>)}<button type="button" className="mp-danger" onClick={()=>setZones(zones.filter((_,j)=>j!==i))}>Remove band</button></div>)}<div className="mp-actions"><button type="button" className="mp-secondary" disabled={zones.length>=20} onClick={()=>setZones([...zones,{minDistanceKm:zones.at(-1)?.maxDistanceKm??0,maxDistanceKm:Number(zones.at(-1)?.maxDistanceKm??0)+5,fee:0}])}>Add distance band</button><button disabled={busy}>Save delivery fees</button></div></form></section>;
}
