'use client';
import { useCallback, useEffect, useState } from 'react';
import './merchant.css';
type Row = Record<string, any>;
const stages: Record<string,string[]> = { PENDING:['ACCEPTED','REJECTED'], ACCEPTED:['PREPARING'], PREPARING:['READY_FOR_PICKUP'] };
const label = (s: string) => s.toLowerCase().replaceAll('_',' ');
const money = (v: unknown) => `${Number(v || 0).toLocaleString()} RWF`;
export default function MerchantPortal() {
 const [memberships,setMemberships]=useState<Row[]>([]),[tenant,setTenant]=useState(''),[role,setRole]=useState('');
 const [tab,setTab]=useState('Overview'),[rows,setRows]=useState<Row[]>([]),[categories,setCategories]=useState<Row[]>([]),[branches,setBranches]=useState<Row[]>([]);
 const [context,setContext]=useState<Row>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[edit,setEdit]=useState<Row|null>(null);
 const canWrite=['OWNER','ADMIN','MANAGER'].includes(role),canAdmin=['OWNER','ADMIN'].includes(role);
 const call=useCallback(async(path:string,method='GET',body?:unknown)=>{
  const res=await fetch(`/api/merchant/${path}`,{method,headers:{'content-type':'application/json','x-tenant-id':tenant},...(body===undefined?{}:{body:JSON.stringify(body)})});
  const data=res.status===204?null:await res.json();if(!res.ok)throw Error(data.message||label(data.error||'Request failed'));return data;
 },[tenant]);
 const session=async()=>{try{const r=await fetch('/api/merchant-session/me');if(r.ok){const d=await r.json();setMemberships(d.memberships);setTenant(d.memberships[0]?.tenant.id||'');setRole(d.memberships[0]?.role||'');}}finally{setReady(true);}};
 useEffect(()=>{void session();},[]);
 const load=useCallback(async()=>{
  if(!tenant)return;setBusy(true);setError('');try{
   const [c,cats,bs]=await Promise.all([call('context'),call('categories'),call('fulfillment')]);setContext(c);setCategories(cats);setBranches(bs);
   const paths:Record<string,string>={Orders:'orders',Products:'products',Categories:'categories',Drivers:'drivers',Promotions:'promotions',Support:'support',Finance:'finance'};
   const result=paths[tab]?await call(paths[tab]):[];setRows(Array.isArray(result)?result:result.entries||[]);
  }catch(e){setError(String(e).replace('Error: ',''));}finally{setBusy(false);}
 },[tenant,tab,call]);
 useEffect(()=>{void load();},[load]);
 const mutate=async(path:string,method:string,body?:unknown)=>{setBusy(true);setError('');try{await call(path,method,body);setEdit(null);await load();}catch(e){setError(String(e).replace('Error: ',''));}finally{setBusy(false);}};
 const upload=async(file:File)=>{if(file.size>5*1024*1024){setError('Choose an image smaller than 5 MB.');return;}
  setBusy(true);try{const base64=await new Promise<string>((ok,fail)=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(',')[1]);r.onerror=fail;r.readAsDataURL(file);});const d=await call('media','POST',{base64});setEdit(v=>v?{...v,imageUrl:d.url}:v);}catch(e){setError(String(e));}finally{setBusy(false);}};
 if(!ready)return <main className="mp-loading">Opening your business…</main>;
 if(!tenant)return <main className="mp-login"><div className="mp-login-story"><span>FIDA • MERCHANT</span><h1>Your business.<br/>More possibilities.</h1><p>Manage your menu, orders and delivery team in one place.</p><div className="mp-orb">✦</div></div><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const r=await fetch('/api/merchant-session/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:f.get('email'),password:f.get('password')})});const d=await r.json();if(!r.ok)throw Error(d.message||label(d.error));await session();}catch(e){setError(String(e));}finally{setBusy(false);}}}><h2>Welcome back</h2><p>Sign in with your merchant account.</p><label>Email<input name="email" type="email" required autoComplete="username"/></label><label>Password<input name="password" type="password" required autoComplete="current-password"/></label>{error&&<p role="alert" className="mp-error">{error}</p>}<button disabled={busy}>Sign in to your business →</button></form></main>;
 const field=(key:string,title:string,type='text',required=false)=><label>{title}<input type={type} required={required} value={edit?.[key]??''} onChange={e=>setEdit(v=>({...v,[key]:type==='number'?e.target.valueAsNumber:e.target.value}))}/></label>;
 const name=context.tenant?.name||'Your business';
 return <div className="mp"><aside className="mp-sidebar"><a className="mp-brand" href="/merchant">Fida<span>business</span></a><nav>{['Overview','Orders','Products','Categories','Drivers','Business','Promotions','Finance','Support'].filter(t=>t!=='Finance'||canAdmin).map(t=><button key={t} className={t===tab?'selected':''} onClick={()=>{setTab(t);setEdit(null);}}>{t}</button>)}</nav><div className="mp-tenant"><select aria-label="Select business" value={tenant} onChange={e=>{setTenant(e.target.value);setRole(memberships.find(m=>m.tenant.id===e.target.value)?.role||'');}}>{memberships.map(m=><option key={m.tenant.id} value={m.tenant.id}>{m.tenant.name}</option>)}</select><small>{label(role)}</small><button onClick={async()=>{await fetch('/api/merchant-session/logout',{method:'POST'});setTenant('');setMemberships([]);}}>Sign out</button></div></aside><main className="mp-main"><header><div><span className="mp-eyebrow">YOUR BUSINESS, AT A GLANCE</span><h1>{tab==='Overview'?`Hello, ${name}`:tab}</h1></div><button className="mp-secondary" disabled={busy} onClick={()=>void load()}>{busy?'Updating…':'Refresh'}</button></header>{error&&<div role="alert" className="mp-error">{error}</div>}
 {tab==='Overview'&&<><section className="mp-hero"><div><span>READY FOR THE NEXT ORDER?</span><h2>Great food.<br/>Happy customers.</h2><p>Keep your menu fresh and your deliveries moving.</p><button onClick={()=>setTab('Orders')}>Open order queue →</button></div><div className="mp-hero-art">✦<span>Fida</span></div></section><section className="mp-stats">{['orders','products','categories','drivers'].map((k,i)=><button className={`mp-stat mp-tint-${i}`} key={k} onClick={()=>setTab(k[0].toUpperCase()+k.slice(1))}><strong>{context.counts?.[k]??0}</strong><span>{label(k)}</span></button>)}</section><section className="mp-panel"><h2>Store availability</h2><p>{context.tenant?.isAcceptingOrders?'Your store is accepting orders.':'Your store is paused.'}</p>{canAdmin&&<button onClick={()=>void mutate('settings','PATCH',{isAcceptingOrders:!context.tenant?.isAcceptingOrders})}>{context.tenant?.isAcceptingOrders?'Pause orders':'Open store'}</button>}</section></>}
 {['Products','Categories','Drivers','Promotions'].includes(tab)&&<div className="mp-toolbar"><p>{rows.length} {tab.toLowerCase()}</p>{(tab==='Drivers'?canAdmin:canWrite)&&<button onClick={()=>setEdit({kind:tab,...(tab==='Drivers'?{mode:'create',maxConcurrentOrders:3}:{}),...(tab==='Promotions'?{percent:10,maxDiscount:2000,maxUses:100,minimumOrder:0}:{})})}>+ Add {tab==='Categories'?'category':tab.slice(0,-1).toLowerCase()}</button>}{tab==='Drivers'&&canAdmin&&<button className="mp-secondary" onClick={()=>setEdit({kind:'Drivers',mode:'enroll'})}>Enroll existing driver</button>}</div>}
 <section className={tab==='Products'?'mp-product-grid':'mp-list'}>{rows.map(row=><article className="mp-panel" key={row.id||row.reference}>
 {tab==='Products'&&<><div className="mp-product-image">{row.imageUrl?<img src={row.imageUrl} alt={row.name}/>:<span>✦</span>}</div><h3>{row.name}</h3><p>{row.category?.name||'Uncategorised'}</p><strong>{money(row.price)}</strong><span className={`mp-badge ${row.isActive&&row.isAvailable?'green':''}`}>{!row.isActive?'Suspended':row.isAvailable?'Available':'Sold out'}</span></>}
 {tab==='Categories'&&<><h3>{row.name}</h3><span className="mp-badge">{row.isActive?'Active':'Suspended'}</span></>}
 {tab==='Drivers'&&<><h3>{row.displayName||[row.user?.firstName,row.user?.lastName].filter(Boolean).join(' ')||row.user?.email}</h3><p>{row.user?.email} · <a href={`tel:${row.user?.phone||''}`}>{row.user?.phone}</a></p><p>{row.branch?.name||'All branches'} · {row.vehicleType} · {row.vehiclePlate||'No plate'}</p><span className="mp-badge">{row.isActive?(row.isOnline?'Online':'Offline'):'Suspended'} · Capacity {row.maxConcurrentOrders}</span></>}
 {['Products','Categories','Drivers'].includes(tab)&&(tab==='Drivers'?canAdmin:canWrite)&&<div className="mp-actions"><button className="mp-secondary" onClick={()=>setEdit({...row,kind:tab})}>Edit</button><button className="mp-secondary" disabled={busy} onClick={()=>void mutate(`${tab.toLowerCase()}/${row.id}`,'PATCH',{isActive:!row.isActive})}>{row.isActive?'Suspend':'Activate'}</button>{tab!=='Drivers'&&<button className="mp-danger" disabled={busy} onClick={()=>{if(confirm(`Delete ${row.name}? ${tab==='Categories'?'Products in this category will be hidden.':''} Order history is preserved.`))void mutate(`${tab.toLowerCase()}/${row.id}`,'DELETE');}}>Delete</button>}</div>}
 {tab==='Orders'&&<><div className="mp-row"><h3>{row.orderNumber}</h3><span className="mp-badge green">{label(row.status)}</span></div><p>{row.customer?.firstName} · <a href={`tel:${row.customer?.phone||''}`}>{row.customer?.phone||'No phone'}</a></p><p>{row.deliveryAddress||'Customer pickup'}</p>{row.items?.map((item:Row)=><p key={item.id}>{item.quantity} × {item.productName}</p>)}<strong>{money(row.total)}</strong><div className="mp-actions">{canWrite&&(stages[row.status]||(row.status==='READY_FOR_PICKUP'&&row.fulfillmentType==='PICKUP'?['COMPLETED']:[])).map(status=><button key={status} disabled={busy} onClick={()=>void mutate(`orders/${row.id}/status`,'PATCH',{status})}>{label(status)}</button>)}</div></>}
 {tab==='Promotions'&&<><h3>{row.code} · {row.percent}% off</h3><p>{row.usedCount}/{row.maxUses} redemptions · Up to {money(row.maxDiscount)}</p><p>Expires {new Date(row.expiresAt).toLocaleString()}</p>{canWrite&&<button disabled={busy} onClick={()=>void mutate(`promotions/${row.id}`,'PATCH',{isActive:!row.isActive})}>{row.isActive?'Pause':'Activate'}</button>}</>}
 {tab==='Support'&&<><h3>{row.subject}</h3><p>{row.description}</p><span className="mp-badge">{row.status}</span>{row.resolution&&<p>{row.resolution}</p>}{canWrite&&row.status!=='RESOLVED'&&<button onClick={()=>setEdit({...row,kind:'Support'})}>Resolve case</button>}</>}
 {tab==='Finance'&&<><h3>{label(row.kind)}</h3><strong>{money(row.amount)}</strong><p>{row.reference} · {new Date(row.createdAt).toLocaleDateString()}</p></>}
 </article>)}</section>
 {['Orders','Products','Categories','Drivers','Promotions','Support','Finance'].includes(tab)&&!busy&&!rows.length&&<div className="mp-empty"><span>✦</span><h2>No {tab.toLowerCase()} yet</h2><p>Your business activity will appear here.</p></div>}
 {tab==='Business'&&branches.map(b=><section className="mp-panel" key={b.id}><h2>{b.name}</h2><p>{[b.addressLine,b.city].filter(Boolean).join(', ')}</p><p>{b.isAcceptingOrders?'Accepting orders':'Paused'} · {b.pickupEnabled?'Pickup enabled':'Pickup disabled'} · {b.deliveryEnabled?'Delivery enabled':'Delivery disabled'}</p>{b.closedUntil&&<p>Closed until {new Date(b.closedUntil).toLocaleString()}</p>}{canAdmin&&<div className="mp-actions"><button onClick={()=>setEdit({...b,kind:'Hours',openingHours:b.openingHours||Array(7).fill(null)})}>Opening hours</button><button className="mp-secondary" onClick={()=>void mutate(`branches/${b.id}/hours`,'PATCH',{isAcceptingOrders:!b.isAcceptingOrders})}>{b.isAcceptingOrders?'Pause branch':'Open branch'}</button><button className="mp-secondary" onClick={()=>void mutate(`branches/${b.id}/fulfillment`,'PATCH',{pickupEnabled:!b.pickupEnabled})}>Toggle pickup</button><button className="mp-secondary" onClick={()=>void mutate(`branches/${b.id}/fulfillment`,'PATCH',{deliveryEnabled:!b.deliveryEnabled})}>Toggle delivery</button></div>}</section>)}
 </main>{edit&&<div className="mp-overlay"><form className="mp-dialog" onSubmit={async e=>{e.preventDefault();const {kind,id,...values}=edit;if(kind==='Products'){const payload={name:values.name,price:values.price,categoryId:values.categoryId||null,description:values.description||'',imageUrl:values.imageUrl||null,options:values.options||[]};if(id){await mutate(`products/${id}`,'PATCH',{...payload,imageUrl:values.imageUrl||null,options:values.options||[]});}else{setBusy(true);try{await call('products','POST',payload);setEdit(null);await load();}catch(e){setError(String(e));}finally{setBusy(false);}}}else if(kind==='Categories')await mutate(id?`categories/${id}`:'categories',id?'PATCH':'POST',{name:values.name});else if(kind==='Drivers'){if(id){await mutate(`drivers/${id}/details`,'PATCH',{displayName:values.displayName||`${values.user.firstName||''} ${values.user.lastName||''}`.trim(),vehiclePlate:values.vehiclePlate||'',vehicleType:values.vehicleType||'MOTORCYCLE',maxConcurrentOrders:values.maxConcurrentOrders});}else await mutate(values.mode==='enroll'?'drivers':'drivers/create','POST',values);}else if(kind==='Hours')await mutate(`branches/${id}/hours`,'PATCH',{openingHours:values.openingHours,closedUntil:values.closedUntil?new Date(values.closedUntil).toISOString():null});else if(kind==='Support')await mutate(`support/${id}`,'PATCH',{resolution:values.resolution,status:'RESOLVED'});else if(kind==='Promotions')await mutate('promotions','POST',values);}}><div className="mp-row"><h2>{edit.id?'Edit':'Add'} {edit.kind==='Hours'?'opening hours':edit.kind.toLowerCase()}</h2><button type="button" className="mp-secondary" onClick={()=>setEdit(null)} aria-label="Close">×</button></div>
 {['Products','Categories'].includes(edit.kind)&&field('name','Name','text',true)}
 {edit.kind==='Products'&&<>{field('price','Price (RWF)','number',true)}{field('description','Description')}<label>Category<select value={edit.categoryId||''} onChange={e=>setEdit({...edit,categoryId:e.target.value})}><option value="">Uncategorised</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><fieldset><legend>Choices and add-ons</legend>{(edit.options||[]).map((o:Row,i:number)=><div className="mp-row" key={i}><input aria-label="Choice name" placeholder="Extra cheese" value={o.name} onChange={e=>setEdit({...edit,options:edit.options.map((v:Row,j:number)=>j===i?{...v,name:e.target.value}:v)})}/><input aria-label="Extra price" type="number" min="0" value={o.price} onChange={e=>setEdit({...edit,options:edit.options.map((v:Row,j:number)=>j===i?{...v,price:e.target.valueAsNumber}:v)})}/><button type="button" className="mp-secondary" onClick={()=>setEdit({...edit,options:edit.options.filter((_:Row,j:number)=>j!==i)})}>Remove</button></div>)}<button type="button" className="mp-secondary" onClick={()=>setEdit({...edit,options:[...(edit.options||[]),{name:'',price:0}]})}>Add choice</button></fieldset><label>Product photo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{if(e.target.files?.[0])void upload(e.target.files[0]);}}/></label>{edit.imageUrl&&<><img className="mp-preview" alt="Product preview" src={edit.imageUrl}/><button type="button" className="mp-secondary" onClick={()=>setEdit({...edit,imageUrl:null})}>Remove photo</button></>}</>}
 {edit.kind==='Drivers'&&(edit.id?<>{field('displayName','Driver display name')}{field('vehiclePlate','Vehicle plate')}{field('maxConcurrentOrders','Maximum simultaneous orders','number',true)}</>:edit.mode==='enroll'?field('emailOrPhone','Existing driver email or phone','text',true):<>{field('firstName','First name','text',true)}{field('lastName','Last name')}{field('email','Email','email',true)}{field('phone','Phone','tel',true)}{field('password','Initial password','password',true)}</>)}
 {edit.kind==='Hours'&&<>{['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map((d,i)=><div className="mp-hours" key={d}><label><input type="checkbox" checked={edit.openingHours[i]!==null} onChange={e=>{const hours=[...edit.openingHours];hours[i]=e.target.checked?{open:'09:00',close:'18:00'}:null;setEdit({...edit,openingHours:hours});}}/>{d}</label>{edit.openingHours[i]&&(['open','close'] as const).map(k=><input key={k} aria-label={`${d} ${k}`} type="time" required value={edit.openingHours[i][k]} onChange={e=>{const hours=[...edit.openingHours];hours[i]={...hours[i],[k]:e.target.value};setEdit({...edit,openingHours:hours});}}/>)}</div>)}{field('closedUntil','Temporary closure until','datetime-local')}<small>Opening hours use your business time zone. Overnight hours are supported.</small></>}
 {edit.kind==='Promotions'&&<>{field('code','Promo code','text',true)}{field('percent','Discount percent','number',true)}{field('maxDiscount','Maximum discount (RWF)','number',true)}{field('minimumOrder','Minimum order (RWF)','number',true)}{field('maxUses','Maximum redemptions','number',true)}{field('expiresAt','Expires','datetime-local',true)}</>}
 {edit.kind==='Support'&&field('resolution','Resolution','text',true)}
 {error&&<p role="alert" className="mp-error">{error}</p>}<button disabled={busy}>{busy?'Saving…':'Save changes'}</button></form></div>}</div>;
}
