'use client';
import {useEffect,useState} from 'react';
type Row=Record<string,any>;
export function StaffSettings({call,branches}:{call:(p:string,m?:string,b?:unknown)=>Promise<any>;branches:Row[]}){
 const [rows,setRows]=useState<Row[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=()=>call('staff').then(setRows);
 useEffect(()=>{load().catch(e=>setError(String(e)));},[call]);
 const change=async(id:string,body:unknown)=>{setBusy(true);try{await call(`staff/${id}`,'PATCH',body);await load();}catch(e){setError(String(e));}finally{setBusy(false);}};
 return <section className="mp-panel"><h2>Staff accounts</h2><p>Kitchen crew can view assigned orders, prepare them and toggle stock. They cannot access finance, payouts, promotions or staff management.</p>{error&&<p className="mp-error" role="alert">{error}</p>}<form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;setBusy(true);setError('');try{await call('staff','POST',Object.fromEntries(new FormData(form)));form.reset();await load();}catch(e){setError(String(e));}finally{setBusy(false);}}}><div className="mp-form-grid"><label>Name<input name="firstName" required/></label><label>Email<input type="email" name="email" required/></label><label>Initial password<input type="password" name="password" required minLength={12} maxLength={128} autoComplete="new-password"/></label><label>Role<select name="role"><option value="KITCHEN_CREW">Kitchen crew</option><option value="MANAGER">Manager</option></select></label><label>Branch<select name="branchId"><option value="">All branches</option>{branches.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></label></div><button disabled={busy}>Create staff account</button></form>{rows.map(r=><article className="mp-panel" key={r.id}><h3>{r.user.firstName||r.user.email}</h3><p>{r.user.email} · {r.role} · {r.isActive?'Active':'Suspended'}</p>{['MANAGER','KITCHEN_CREW','STAFF'].includes(r.role)&&<div className="mp-actions"><button disabled={busy} onClick={()=>void change(r.id,{isActive:!r.isActive})}>{r.isActive?'Suspend':'Activate'}</button><select aria-label="Staff role" value={r.role} disabled={busy} onChange={e=>void change(r.id,{role:e.target.value})}>{r.role==='STAFF'&&<option>STAFF</option>}<option>MANAGER</option><option>KITCHEN_CREW</option></select></div>}</article>)}</section>;
}
