'use client';
import {useEffect,useState} from 'react';
type Row=Record<string,any>;
export function ApplicationReview(){
 const [rows,setRows]=useState<Row[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notes,setNotes]=useState<Record<string,string>>({});
 const load=async()=>{const r=await fetch('/api/admin/merchant-applications');const d=await r.json();if(!r.ok)throw Error(d.message||d.error);setRows(d);};
 useEffect(()=>{load().catch(e=>setError(String(e)));},[]);
 const review=async(row:Row,action:string)=>{setBusy(true);setError('');try{const r=await fetch(`/api/admin/merchant-applications/${row.id}/review`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,reason:notes[row.id]})});const d=await r.json();if(!r.ok)throw Error(d.message||d.error);await load();}catch(e){setError(String(e));}finally{setBusy(false);}};
 return <section><h2>Merchant verification</h2>{error&&<p className="mp-error" role="alert">{error}</p>}{!rows.length&&<p>No submitted applications.</p>}{rows.map(r=><article className="mp-panel" key={r.id}><span className="mp-badge">{r.status}</span><h3>{r.payload.name}</h3><img className="mp-preview" src={r.payload.coverUrl} alt={`${r.payload.name} cover`}/><p>Legal entity: {r.payload.legalName} · Tax ID: {r.payload.taxId}</p><p>{r.payload.addressLine}, {r.payload.city}</p><p>Coordinates: {r.payload.latitude}, {r.payload.longitude}</p><p>{r.payload.merchantType} · {r.payload.cuisineTags?.join(', ')} · {r.payload.timezone}</p>{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((day,i)=><p key={day}>{day}: {(Array.isArray(r.payload.openingHours[i])?r.payload.openingHours[i]:r.payload.openingHours[i]?[r.payload.openingHours[i]]:[]).map((w:Row)=>`${w.open}–${w.close}`).join(', ')||'Closed'}</p>)}{r.status==='SUBMITTED'?<><label>Review note<textarea required maxLength={2000} value={notes[r.id]||''} onChange={e=>setNotes({...notes,[r.id]:e.target.value})}/></label><div className="mp-actions"><button disabled={busy||!notes[r.id]?.trim()} onClick={()=>void review(r,'APPROVE')}>Approve store</button><button className="mp-danger" disabled={busy||!notes[r.id]?.trim()} onClick={()=>void review(r,'REJECT')}>Reject application</button></div></>:<p>{r.reviewReason} · {new Date(r.reviewedAt).toLocaleString()}</p>}</article>)}</section>;
}
