'use client';
import {useCallback,useEffect,useState} from 'react';
import '../merchant/merchant.css';
import {DocumentView} from '../merchant/document-view';
type Row=Record<string,any>;
export default function BusinessOperations(){
 const [document,setDocument]=useState<Row|null>(null);
 const [authorized,setAuthorized]=useState(false),[ready,setReady]=useState(false),[tab,setTab]=useState('Fleet'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[data,setData]=useState<any>(null);
 const call=async(path:string,method='GET',body?:unknown)=>{const r=await fetch(`/api/admin/${path}`,{method,headers:{'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});const d=await r.json();if(!r.ok)throw Error(d.message||d.error);return d;};
 useEffect(()=>{fetch('/api/session/me').then(r=>setAuthorized(r.ok)).finally(()=>setReady(true));},[]);
 const load=useCallback(async()=>{if(!authorized)return;setBusy(true);try{setData(await call(`business/${{Fleet:'fleet',Refunds:'refunds',Ledger:'ledger',Performance:'performance',Documents:'documents'}[tab]}`));setError('');}catch(e){setError(String(e));}finally{setBusy(false);}},[tab,authorized]);useEffect(()=>{void load();},[load]);
 const mutate=async(path:string,body:unknown,method='POST')=>{setBusy(true);try{await call(path,method,body);await load();}catch(e){setError(String(e));}finally{setBusy(false);}};
 const input=(name:string,type='text',placeholder=name)=> <input name={name} type={type} placeholder={placeholder} aria-label={placeholder} required/>;
 if(!ready)return <main className="mp-loading">Loading…</main>;
 if(!authorized)return <main className="mp"><section className="mp-panel"><h1>Platform operations</h1><p>Sign in using your platform administrator account.</p><a href="/">Open administrator sign-in</a></section></main>;
 return <main className="mp" style={{padding:'32px',maxWidth:1250,margin:'auto'}}><header className="mp-row"><div><a href="/">← Control center</a><h1>Business operations</h1></div><button disabled={busy} onClick={()=>void load()}>Refresh</button></header><nav className="mp-actions">{['Fleet','Refunds','Ledger','Documents','Performance'].map(t=><button key={t} className={t===tab?'':'mp-secondary'} onClick={()=>{setTab(t);setData(null);}}>{t}</button>)}</nav>{error&&<p role="alert" className="mp-error">{error}</p>}<br/>
 {tab==='Fleet'&&data?.drivers&&<><form className="mp-panel" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate('business/fleet/enroll',{email:f.get('email')});}}><h2>Enroll a Fida fleet driver</h2><p>Use an existing Fida account. Merchant drivers remain managed by their merchant.</p>{input('email','email','Driver account email')}<br/><button disabled={busy}>Enroll driver</button></form>{Array.from(new Map<string,Row>(data.drivers.filter((d:Row)=>d.operator).map((d:Row)=>[d.operator.id,d.operator])).values()).map((op:Row)=><form className="mp-panel" key={op.id} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate(`business/operators/${op.id}/pay`,{driverBasePay:Number(f.get('base')),driverPerKmPay:Number(f.get('km'))},'PATCH');}}><h3>{op.name} · Driver pay rates</h3><div className="mp-form-grid"><label>Base pay (order currency)<input type="number" min="0" step="0.01" required name="base" defaultValue={op.driverBasePay??''}/></label><label>Per delivery kilometre<input type="number" min="0" step="0.01" required name="km" defaultValue={op.driverPerKmPay??''}/></label></div><button disabled={busy}>Save future offer rates</button></form>)}<div className="mp-product-grid">{data.drivers.map((d:Row)=><article className="mp-panel" key={d.id}><h3>{d.user.firstName} {d.user.lastName}</h3><p>{d.user.email}</p><span className="mp-badge">{d.isOnline?'Online':'Offline'} · Capacity {d.maxConcurrentOrders}</span></article>)}</div><section className="mp-panel"><h2>Dispatch ready orders</h2>{data.deliveries.map((d:Row)=><form key={d.id} className="mp-panel" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate('business/fleet/dispatch',{deliveryId:d.id,driverId:f.get('driverId')});}}><strong>{d.order.orderNumber} · {d.order.status}</strong><p>{d.status}</p>{d.status==='UNASSIGNED'&&d.order.status==='READY_FOR_PICKUP'&&<><select required name="driverId" aria-label="Assign driver"><option value="">Choose available driver</option>{data.drivers.filter((v:Row)=>v.isActive&&v.isOnline&&v.isAvailable).map((v:Row)=><option key={v.id} value={v.id}>{v.user.firstName} {v.user.lastName}</option>)}</select><br/><button disabled={busy}>Assign delivery</button></>}</form>)}</section></>}
 {tab==='Documents'&&Array.isArray(data)&&data.map((d:Row)=><article className="mp-panel" key={d.id}><h3>{d.payload?.title} · {d.number}</h3><p>{d.payload?.recipient} · {d.payload?.total} {d.payload?.currency}</p><button onClick={()=>setDocument(d)}>View / download PDF</button></article>)}
 {document&&<DocumentView document={document} onClose={()=>setDocument(null)}/>}
 {tab==='Refunds'&&Array.isArray(data)&&data.map((r:Row)=><form className="mp-panel" key={r.id} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate(`business/refunds/${r.id}`,{status:f.get('status'),resolution:f.get('resolution'),externalReference:f.get('externalReference')},'PATCH');}}><h3>Order {r.orderId}</h3><strong>{Number(r.amount).toLocaleString()} RWF · {r.status}</strong><p>{r.reason}</p>{r.status!=='REFUNDED'&&<><select name="status" aria-label="Refund decision"><option value="APPROVED">Approve refund request</option><option value="REJECTED">Reject request</option>{r.status==='APPROVED'&&<option value="REFUNDED">Record completed refund</option>}</select><label>Resolution{input('resolution')}</label><label>External refund receipt<input name="externalReference" placeholder="Required when recording a completed refund"/></label><p>Recording a refund does not transfer money. Complete it through your payment provider first.</p><button disabled={busy}>Save decision</button></>}</form>)}
 {tab==='Ledger'&&<><div className="mp-product-grid">{['Commission remittance','Merchant payout'].map((title,i)=><form className="mp-panel" key={title} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate(i?'business/payouts':'finance/remittances',{tenantId:f.get('tenantId'),amount:Number(f.get('amount')),reference:f.get('reference'),note:f.get('note')});}}><h3>{title}</h3><p>Record a verified external payment.</p><label>Merchant ID{input('tenantId')}</label><label>Amount{input('amount','number')}</label><label>Receipt reference{input('reference')}</label><label>Note<input name="note"/></label><button disabled={busy}>Record payment</button></form>)}</div><section className="mp-panel"><h2>Ledger entries</h2><div style={{overflowX:'auto'}}><table style={{width:'100%',textAlign:'left'}}><thead><tr><th>Date</th><th>Merchant</th><th>Type</th><th>Amount</th><th>Reference</th></tr></thead><tbody>{Array.isArray(data)&&data.map((r:Row)=><tr key={r.id}><td>{new Date(r.createdAt).toLocaleDateString()}</td><td>{r.tenantId}</td><td>{r.kind}</td><td>{Number(r.amount).toLocaleString()}</td><td>{r.reference}</td></tr>)}</tbody></table></div></section></>}
 {tab==='Performance'&&data?.orders&&<><section className="mp-stats">{[['Mean delivery (min)',data.meanDeliveryMinutes?.toFixed(1)||'—'],['Delivery sample',data.deliverySample],['Repeat customers',data.repeatCustomers],['Pending push events',data.pendingPushEvents]].map(([name,value],i)=><div className={`mp-panel mp-tint-${i}`} key={name}><h2>{value}</h2><p>{name}</p></div>)}</section><section className="mp-panel"><h2>Last 30 days</h2>{data.orders.map((r:Row)=><p key={r.status}>{r.status}: {r._count._all} orders · {Number(r._sum.total||0).toLocaleString()} RWF</p>)}<p>Average review: {data.reviews._avg.rating?.toFixed(1)||'No reviews'} · {data.reviews._count._all} reviews</p></section></>}
 </main>;
}
