import { Prisma } from '@fida/database/client';

/** Issued inside the same transaction as completion. Retries never alter a document. */
export async function issueOrderDocuments(tx: Prisma.TransactionClient, orderId: string) {
 const order = await tx.order.findUniqueOrThrow({where:{id:orderId},include:{tenant:true,branch:true,customer:{select:{firstName:true,lastName:true}},items:true}});
 if (order.status !== 'COMPLETED') return;
 const currency=order.tenant.currency;
 const lines=order.items.map(i=>({description:i.productName,quantity:i.quantity,unitPrice:i.unitPrice.toString(),amount:i.totalPrice.toString(),discount:i.discount.toString(),tax:i.tax.toString()}));
 const common={orderNumber:order.orderNumber,currency,orderDate:order.createdAt.toISOString(),issuedAt:order.updatedAt.toISOString(),merchantName:order.tenant.name,merchantAddress:[order.branch.addressLine,order.branch.city].filter(Boolean).join(', ')};
 const receipt={...common,title:'Order receipt',issuer:order.tenant.name,recipient:[order.customer.firstName,order.customer.lastName].filter(Boolean).join(' ')||'Customer',paymentMethod:order.paymentMethod,paymentStatus:order.paymentStatus,lines,subtotal:order.subtotal.toString(),discount:order.discount.toString(),tax:order.tax.toString(),taxLabel:order.taxLabel,deliveryFee:order.deliveryFee.toString(),serviceFee:order.serviceFee.toString(),total:order.total.toString(),note:'Order receipt generated by Fida. Request an EBM fiscal receipt from the merchant where applicable.'};
 const invoice={...common,title:'Commission invoice',issuer:'Fidalix Ltd',recipient:order.tenant.name,lines:[{description:`Marketplace commission · ${order.orderNumber} · ${order.platformCommissionPercent}%`,quantity:1,unitPrice:order.platformCommissionAmount.toString(),amount:order.platformCommissionAmount.toString()}],subtotal:order.platformCommissionAmount.toString(),total:order.platformCommissionAmount.toString(),note:'Commercial commission invoice. Payment and credit adjustments are shown separately in your statement. This is not an EBM fiscal invoice.'};
 for (const [kind,prefix,payload] of [['CUSTOMER_RECEIPT','RCPT',receipt],['COMMISSION_INVOICE','COM',invoice]] as const) {
  await tx.businessDocument.upsert({where:{orderId_kind:{orderId,kind}},update:{},create:{orderId,kind,number:`${prefix}-${order.orderNumber}`,tenantId:order.tenantId,customerId:order.customerId,payload:payload as Prisma.InputJsonValue}});
 }
}
export async function issueRefundDocuments(tx:Prisma.TransactionClient,orderId:string){
 const originals=await tx.businessDocument.findMany({where:{orderId,kind:{in:['CUSTOMER_RECEIPT','COMMISSION_INVOICE']}}});
 for(const original of originals){
  const p=original.payload as Record<string,Prisma.JsonValue>;
  const kind=original.kind==='CUSTOMER_RECEIPT'?'CUSTOMER_CREDIT':'COMMISSION_CREDIT';
  const amount=new Prisma.Decimal(String(p.total));
  const payload={...p,title:'Credit note',originalNumber:original.number,issuedAt:new Date().toISOString(),lines:[{description:`Full refund · ${original.number}`,quantity:1,unitPrice:amount.negated().toString(),amount:amount.negated().toString()}],subtotal:amount.negated().toString(),discount:'0',tax:'0',deliveryFee:'0',serviceFee:'0',total:amount.negated().toString(),paymentStatus:'REFUNDED'};
  await tx.businessDocument.upsert({where:{orderId_kind:{orderId,kind}},update:{},create:{orderId,kind,number:`CR-${original.number}`,tenantId:original.tenantId,customerId:original.customerId,payload:payload as Prisma.InputJsonValue}});
 }
}
